### PR TITLE
CMake Sub-Project Improvements, master branch (2021.04.29.)

### PR DESCRIPTION
**Pull request by krasznaa**
I tried to make the project's configuration more friendly towards being included in another project. (Either using a [git submodule](https://git-scm.com/docs/git-submodule), or with CMake's [FetchContent module](https://cmake.org/cmake/help/latest/module/FetchContent.html).)

I didn't need to do much for this. I turned `CMAKE_CXX_STANDARD` into a cache variable, so that if the parent project uses a different (newer) standard, that would trickle down into the triSYCL sub-project as well. (This has the upside of making the C\+\+ standard configurable from the command line during a "standalone" build as well.)

Plus I disabled the packaging configuration when the project is used as a sub-project in some other project. As that would interfere with how the parent project is trying to package up itself.

### CODE REVIEW

**Comment by keryell** [comment]
Thanks, that looks good, at least according my minimal CMake knowledge.
I have other projects with triSYCL as a submodule. Up to now I was just adding the triSYCL include path to the main project, but obviously something cleaner as you propose is better. :-)
Do you have an example of project using triSYCL this way?

**Comment by krasznaa** [comment]
Unfortunately after all this trouble I ended up not setting up a build like this. :frowning: As I only realised way too late that triSYCL doesn't yet support a couple of function calls that I use in my project... (Basically all of the USM stuff with memory allocation/deallocation/copying.)

However that was really only just the final nail in the coffin. As I could only get to that build failure after giving up on using the triSYCL source as I originally wanted, and just adding the include directory of it to my build without relying on the triSYCL CMake configuration. Exactly as you wrote.

This is because of a problem in range-v3... Which I now realise was fixed just recently with https://github.com/ericniebler/range-v3/issues/1621. (I was picking up an older version in my tests.) If triSYCL could've been used to build my project, I would've spent time on sorting this out. But it was moot after I realised that my build would not work anyway.

Long story short, I was trying to use a configuration along the lines of:

```cmake
# Guard against multiple includes.
include_guard( GLOBAL )

# Look for triSYCL.
find_package( triSYCL QUIET )

# If it's available, then let the user know what's happening, and set up the
# cache variable needed by the SYCL language CMake code.
if( triSYCL_FOUND )
   message( STATUS
      "Found triSYCL: ${triSYCL_DIR} (found version \"${triSYCL_VERSION}\")" )
   set( TRISYCL_INCLUDE_DIR "${TRISYCL_INCLUDE_DIR}" CACHE PATH
      "Path to pick up the triSYCL headers from" )
   return()
endif()

# CMake include(s).
cmake_minimum_required( VERSION 3.11 )
include( FetchContent )

# Look for Range-v3, as it is needed by triSYCL. Set it up if it's not available
# on the build system.
find_package( range-v3 QUIET )
if( range-v3_FOUND )
   message( STATUS
      "Found range-v3: ${range-v3_DIR} (found version \"${range-v3_VERSION}\")" )
else()

   # Tell the user what's happening.
   message( STATUS "Building range-v3 as part of the project" )

   # Declare where to get range-v3 from.
   FetchContent_Declare( range-v3
      URL "https://github.com/ericniebler/range-v3/archive/refs/tags/0.11.0.tar.gz"
      URL_MD5 "97ab1653f3aa5f9e3d8200ee2a4911d3" )

   # Options used in the build of ranges-v3.
   set( RANGES_CXX_STD 17 CACHE STRING
      "C++ standard for ranges-v3" )

   # Get it into the current directory.
   FetchContent_Populate( range-v3 )
   add_subdirectory( "${range-v3_SOURCE_DIR}" "${range-v3_BINARY_DIR}"
      EXCLUDE_FROM_ALL )

endif()

# Tell the user what's happening.
message( STATUS "Downloading triSYCL as part of the project" )

# Declare where to get triSYCL from.
FetchContent_Declare( triSYCL
   GIT_REPOSITORY "https://github.com/triSYCL/triSYCL.git"
   GIT_TAG "fbfc9c4d66fbb342da2f0636dfe00bd204b9ff69" )
FetchContent_Populate( triSYCL )

# Trick the triSYCL build into thinking that it found range-v3. When in fact
# it will just pick up the targets defined by the range-v3 build itself, or by
# our own previous call to find_package(range-v3).
set( range-v3_DIR "${CMAKE_CURRENT_LIST_DIR}" CACHE PATH
   "Path to the range-v3-config.cmake file used by the triSYCL build" FORCE )

# Get it into the current directory.
FetchContent_Populate( triSYCL )
add_subdirectory( "${trisycl_SOURCE_DIR}" "${trisycl_BINARY_DIR}"
   EXCLUDE_FROM_ALL )

# Set up an alias for the triSYCL target with the same name that it has
# when we find triSYCL pre-installed.
add_library( triSYCL::triSYCL ALIAS triSYCL )
```

I also had to create a dummy `range-v3-config.cmake` in my source tree that triSYCL would "find" using its `find_package(range-v3)` call, in order to have it use the range-v3 headers correctly from inside of the build tree.

But again, once I realised that the C\+\+ code would not work, I didn't finish ironing out the kinks on this setup...

**Comment by keryell** [comment]
Yes, as you figured out triSYCL is a SYCL research project to experiment with some features and weird targets but unfortunately far from a full implementation.
Sorry it was not clear enough on the README with "Because of lack of resources this SYCL implementation is very incomplete and should not be used by a normal end-user."
Anyway, I am thinking to have various projects used by triSYCL (range-v3...) as git submodules to ease the usage.

**Comment by krasznaa** [comment]
I think the documentation is okay in this respect. I didn't expect to use triSYCL in any "serious way" in my project. I was mainly trying to demonstrate that my code could compile and run with multiple SYCL implementations. To test that I would not make it super dependent on the Intel implementation's quirks. (The triSYCL code did help me a bit with this. I did realise along the way that one of my include statements was Intel specific, without me realising.)

With the sub-moduling: Do be careful with that. Projects should ideally really only submodule external code that they only use internally. (With `PRIVATE` linking in CMake terms.) And even then, only if they explicitly don't export any of the symbols of that external code. A good example of this is what Microsoft does in [onnxruntime](https://github.com/microsoft/onnxruntime). But unfortunately it's pretty impossible to do with triSYCL, as the whole project is header based. (So by definition every symbol is always exported.)

I'm saying this because otherwise it becomes impossible to include triSYCL into a larger project. One that already has its own version of Range-v3 set up in some way. This is why I rather like to use CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) module, similar to the example that I've shown above. This way the user of my project can either provide their own version of a given external, or if they don't, my code downloads an appropriate version for itself.

It's tedious, I agree. But for header-heavy projects I found this to be the safest / most robust way to go.

**Comment by keryell** [comment]
I looked at CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) module and also [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html) module.
This is quite interesting!
As you say, it is more challenging with a pure header approach. But probably the *"first to record, wins" approach* of FetchContent is a reasonable euristic.
Otherwise I was thinking to a feature like using FetchContent only if the requested module is not available on the system.
But it does not seem to be a feature available by default in FetchContent.
I will try the concept along https://github.com/triSYCL/triSYCL/pull/304

**Pull request merged**
