### PR TITLE
Update nd_item, nd_range, h_item & group according to SYCL 1.2.1 rev 3

### PR DESCRIPTION
**Pull request by keryell**

### CODE REVIEW

**Comment by airlied** [comment]
though it looks like some tests need updating.

**Comment by keryell** [comment]
Ah yes, you are right. I have not compiled with OpenMP enabled on my machine, so I missed some renaming.

**Comment by airlied** [comment]
looks good to merge to me

**Comment by keryell** [comment]
You can merge it if you are happy with it.

**Pull request merged**
