### PR TITLE
start implementing device get_info

### PR DESCRIPTION
**Pull request by airlied**
This is more of a feedback request than a pull request. I know you've indicated you had some ideas for better get_info, and I'm not sure I'm C++ enough to get to boost::hana just yet.

But I've started doing the get_info for devices and have something that starts to pass the CTS test_device test.
the patch 
device: use boost::any to workaround virtual templating issues 
is probably the main one, as it uses boost::any to workaround the virtual templating problem.

### CODE REVIEW

**Comment by keryell** [comment]
This virtual + template issue is a pain.
At least a table description with some macros or data structures to describe the methods & return types like you started is good, whatever the implementation uses.
`boost::any` or even better C++17 `std::any` can work but requires often memory allocation and RTTI.
I guess `get_info` will never be in the critical path of an implementation... :-) 
My plan was to use different virtual functions per returned type, such as `get_info(tag_[returned_type], enum query)` or even a crude `get_info_[returned_type](enum query)` to avoid the type erasure à la `boost::any`.
Boost.Hana could have been used to ease the massaging of the higher-level descriptions of the associations of query/returned data type/default host value/OpenCL query name and then automatically derive the boiling plate code from this meta-description. 
But if you have a running implementation, it is better than this unimplemented plan... :-)

**Comment by keryell** [comment]
Otherwise GitHub does not credit you as a contributor of triSYCL... :-(
I guess this is because you did all your commits with your RedHat e-mail that you did not declare as an alternative in your GitHub account...

**Comment by airlied** [comment]
I've updated my emails now, so hopefully it works.

**Comment by airlied** [comment]
I've updated this, I think we need to drop the get_info test which pretty much only checks the returns from the fixed values that were in the code, which won't work with real devices.

**Comment by airlied** [comment]
@keryell so this seems to be pretty much working now, though whether we want to use boost::any is possibly still an open question, and also the open issue about the display_platform test.

**Comment by airlied** [comment]
Okay repushed with the cleanups merged into the device/platform patches, thanks for review.

**Comment by keryell** [comment]
Great! Thank you.

**Pull request merged**
